server.port=8080

spring.ai.openai.api-key=${OPENAI_API_KEY:YOUR_API_KEY_HERE}
spring.ai.openai.base-url=https://wingman.nimbusplane.io/v1
spring.ai.openai.chat.completions-path=/chat/completions
spring.ai.openai.chat.options.model=wingman
spring.ai.openai.chat.options.temperature=0.2
spring.ai.openai.chat.options.max-tokens=16384
spring.ai.openai.chat.options.frequency-penalty=0.2
spring.ai.openai.chat.options.presence-penalty=0.1
spring.ai.openai.chat.options.top-p=0.95
